version: '3.7'

services:
  checkout_api:
    image: checkout_api_test
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: test
      PORT: 4000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: checkout_api_test
      WAIT_HOSTS: db:5432
    ports:
      - '4000:4000'
      - '9229:9229'
    command: sh -c "/wait && npm run migrate && npm run seed && npm t"
    depends_on:
      - db
  db:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: checkout_api_test
